version: "3"
services:
  api:
    container_name: api-local
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_CONTAINER_NAME: "db"
      DB_PORT: "3306"
      DB_NAME: "development"
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "development"
      TZ: Asia/Tokyo
    ports: 
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db:/docker-entrypoint-initdb.d
      - mysql_volume:/var/lib/mysql
volumes:
  mysql_volume:
    driver: local