version: "3"
services:
  api:
    container_name: api-local
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DB_USER: "postgres"
      DB_PASSWORD: "root"
      DB_CONTAINER_NAME: "db"
      DB_PORT: "5432"
    ports:
      - 4000:4000
    stdin_open: true
    tty: true
    volumes:
      - ./:/app:cached
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: "root"
      TZ: Asia/Tokyo
    ports: 
      - 5432:5432
    volumes:
      - ./db/my.cnf:/etc/postgresql/conf.d/my.cnf
      - ./db:/docker-entrypoint-initdb.d
      - ./db/dbdata:/var/lib/postgresql
volumes:
  mysql_volume:
    driver: local